# Generated by Django 3.2.13 on 2022-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usage_flag',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
