# Generated by Django 3.2.13 on 2022-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20220415_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='auth_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='emailVerified',
            field=models.BooleanField(default=True, verbose_name='이메일인증'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userAgreeGeneral',
            field=models.BooleanField(default=True, verbose_name='이용약관동의'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userAgreePrivate',
            field=models.BooleanField(default=True, verbose_name='개인정보수집동의'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userAgreePromotion',
            field=models.BooleanField(default=True, verbose_name='이벤트 프로모션동의'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userBirth',
            field=models.DateField(default=None, verbose_name='회원생년월일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userCurrentAddress',
            field=models.CharField(max_length=255, null=True, verbose_name='회원현재주소'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userCurrentZip',
            field=models.CharField(max_length=20, null=True, verbose_name='회원현재우편번호'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userGender',
            field=models.CharField(max_length=10, null=True, verbose_name='회원성별'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userMemberPoint',
            field=models.IntegerField(default=0, verbose_name='회원맴버쉽포인트'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userNickname',
            field=models.CharField(max_length=100, null=True, verbose_name='회원닉네임'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userPhone',
            field=models.CharField(max_length=100, null=True, verbose_name='회원연락처'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userPoint',
            field=models.IntegerField(default=0, verbose_name='회원적립금'),
        ),
    ]
