# Generated by Django 3.2.13 on 2022-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20220426_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userPhone',
            field=models.CharField(max_length=20, null=True, verbose_name='회원연락처'),
        ),
    ]
