# Generated by Django 3.2.13 on 2022-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_profile_emailverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userBirth',
            field=models.DateField(default=None, null=True, verbose_name='회원생년월일'),
        ),
    ]
