# Generated by Django 3.2.13 on 2022-04-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_profile_userbirth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emailVerified',
            new_name='userEmailVerified',
        ),
    ]
