# Generated by Django 3.2.13 on 2022-04-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_rename_emailverified_profile_useremailverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
