# Generated by Django 3.2.13 on 2022-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_alter_profile_updateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userCompanyName',
            field=models.CharField(max_length=100, null=True, verbose_name='회사명'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userDelDate',
            field=models.DateTimeField(null=True, verbose_name='회원탈퇴일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userDelFlag',
            field=models.BooleanField(default=False, verbose_name='회원탈퇴플래그'),
        ),
        migrations.AddField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(null=True, upload_to='image/profile/', verbose_name='회원이미지'),
        ),
    ]
