# Generated by Django 3.2.13 on 2022-05-03 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
        ('system_manage', '0002_auto_20220503_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardViewCount', models.IntegerField(default=0, verbose_name='조회수')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_board_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.boardtype')),
                ('sm_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop')),
                ('sm_summernore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.summernote')),
            ],
            options={
                'db_table': 'sm_board',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherNum', models.CharField(max_length=100, null=True, verbose_name='바우처그룹번호')),
                ('voucherTotalPrice', models.IntegerField(verbose_name='총금액')),
                ('voucherTotalQty', models.IntegerField(default=1, verbose_name='총수량')),
                ('voucherQRImg', models.ImageField(null=True, upload_to='image/voucher/%Y/%m/%d/', verbose_name='바우처그룹QR이미지')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wm_voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.vouchertype')),
            ],
            options={
                'db_table': 'vm_voucher',
            },
        ),
        migrations.CreateModel(
            name='WineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewMemo', models.TextField(null=True, verbose_name='메모')),
                ('reviewRate', models.FloatField(default=5, verbose_name='평점')),
                ('reviewPrice', models.IntegerField(verbose_name='구매가격')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
                ('wm_wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.wine')),
            ],
            options={
                'db_table': 'wma_review',
            },
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherDetailNum', models.CharField(max_length=100, null=True, verbose_name='바우처그룹번호')),
                ('voucherPrice', models.IntegerField(verbose_name='제품가격')),
                ('discountRate', models.IntegerField(default=100, verbose_name='할인율')),
                ('wineQty', models.IntegerField(verbose_name='제품개수')),
                ('voucherSubTotal', models.IntegerField(verbose_name='총액')),
                ('vmVoucherUserLocation', models.CharField(max_length=100, null=True, verbose_name='사용처 저장')),
                ('isShipping', models.BooleanField(default=False, verbose_name='배송/픽업')),
                ('voucherExpDate', models.DateTimeField(null=True, verbose_name='만료일')),
                ('voucherQRImg', models.ImageField(null=True, upload_to='image/voucher_detail/%Y/%m/%d/', verbose_name='바우처QR이미지')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.item')),
                ('vm_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.voucher')),
            ],
            options={
                'db_table': 'vm_voucher_detail',
            },
        ),
        migrations.CreateModel(
            name='ShipAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipAddressName', models.CharField(max_length=100, verbose_name='배송지이름')),
                ('shipAddress', models.CharField(max_length=255, null=True, verbose_name='회원현재주소')),
                ('shipZipcode', models.CharField(max_length=20, null=True, verbose_name='배송지우편번호')),
                ('shipUserName', models.CharField(max_length=100, null=True, verbose_name='수령인')),
                ('shopUserPhone', models.CharField(max_length=20, null=True, verbose_name='수령인연락처')),
                ('shipDefault', models.BooleanField(default=False, verbose_name='기본배송지여부')),
                ('shipMemo', models.TextField(null=True, verbose_name='배송메모')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('auth_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='config.profile')),
            ],
            options={
                'db_table': 'profile_shipAddress',
            },
        ),
        migrations.CreateModel(
            name='BoardReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardReply', models.TextField(verbose_name='답변내용')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_board_comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping_mall.board')),
            ],
            options={
                'db_table': 'sm_board_reply',
            },
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardComment', models.TextField(verbose_name='댓글내용')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.board')),
            ],
            options={
                'db_table': 'sm_board_comment',
            },
        ),
    ]
