# Generated by Django 3.2.13 on 2022-04-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0004_alter_profile_userphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipAddressName', models.CharField(max_length=100, verbose_name='배송지이름')),
                ('shipAddress', models.CharField(max_length=255, null=True, verbose_name='회원현재주소')),
                ('shipZipcode', models.CharField(max_length=20, null=True, verbose_name='배송지우편번호')),
                ('shipUserName', models.CharField(max_length=100, null=True, verbose_name='수령인')),
                ('shiopUserPhone', models.CharField(max_length=20, null=True, verbose_name='수령인연락처')),
                ('shipDefault', models.BooleanField(default=False, verbose_name='기본배송지여부')),
                ('regionDes', models.TextField(null=True, verbose_name='배송메모')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('auth_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='config.profile')),
            ],
            options={
                'db_table': 'profile_shipAddress',
            },
        ),
    ]
