# Generated by Django 3.2.13 on 2022-04-26 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_profile_emailverified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_mall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipaddress',
            old_name='regionDes',
            new_name='shipMemo',
        ),
        migrations.AlterField(
            model_name='shipaddress',
            name='auth_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='config.profile'),
        ),
        migrations.CreateModel(
            name='WineReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_wine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wma_review',
            },
        ),
    ]
