# Generated by Django 3.2.13 on 2022-04-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0004_auto_20220425_1554'),
        ('shopping_mall', '0002_auto_20220426_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='winereview',
            name='reviewMemo',
            field=models.TextField(null=True, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='winereview',
            name='reviewRate',
            field=models.FloatField(default=5, verbose_name='평점'),
        ),
        migrations.AlterField(
            model_name='winereview',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_wine', to='system_manage.wine'),
        ),
    ]
