# Generated by Django 3.2.13 on 2022-04-27 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_manage', '0007_auto_20220427_1427'),
        ('shopping_mall', '0003_auto_20220427_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winereview',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winereview',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.wine'),
        ),
    ]
