# Generated by Django 3.2.13 on 2022-04-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0004_auto_20220427_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winereview',
            old_name='wine',
            new_name='wm_wine',
        ),
    ]
