# Generated by Django 3.2.13 on 2022-04-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0005_rename_wine_winereview_wm_wine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipaddress',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='shipaddress',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='winereview',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='winereview',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
