# Generated by Django 3.2.13 on 2022-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0006_auto_20220428_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipaddress',
            name='shiopUserPhone',
        ),
        migrations.AddField(
            model_name='shipaddress',
            name='shopUserPhone',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='수령인연락처'),
        ),
        migrations.AddField(
            model_name='winereview',
            name='reviewPrice',
            field=models.IntegerField(default=0, verbose_name='구매가격'),
        ),
    ]
