# Generated by Django 3.2.13 on 2022-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_mall', '0007_auto_20220502_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipaddress',
            name='shopUserPhone',
            field=models.CharField(max_length=20, null=True, verbose_name='수령인연락처'),
        ),
        migrations.AlterField(
            model_name='winereview',
            name='reviewPrice',
            field=models.IntegerField(verbose_name='구매가격'),
        ),
    ]
