# Generated by Django 3.2.13 on 2022-05-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0023_boardtype'),
        ('shopping_mall', '0008_auto_20220502_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardViewCount', models.IntegerField(default=0, verbose_name='조회수')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_board_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.boardtype')),
                ('sm_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop')),
                ('sm_summernore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.summernote')),
            ],
            options={
                'db_table': 'sm_board',
            },
        ),
        migrations.CreateModel(
            name='BoardReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardReply', models.TextField(verbose_name='답변내용')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_board_comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping_mall.board')),
            ],
            options={
                'db_table': 'sm_board_reply',
            },
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardComment', models.TextField(verbose_name='댓글내용')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.board')),
            ],
            options={
                'db_table': 'sm_board_comment',
            },
        ),
    ]
