# Generated by Django 3.2.13 on 2022-05-02 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0024_auto_20220502_1802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_mall', '0009_board_boardcomment_boardreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherNum', models.CharField(max_length=100, null=True, verbose_name='바우처그룹번호')),
                ('voucherTotalPrice', models.IntegerField(verbose_name='총금액')),
                ('voucherTotalQty', models.IntegerField(default=1, verbose_name='총수량')),
                ('voucherQRImg', models.ImageField(null=True, upload_to='image/voucher/%Y/%m/%d/', verbose_name='바우처그룹QR이미지')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wm_voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.vouchertype')),
            ],
            options={
                'db_table': 'vm_voucher',
            },
        ),
        migrations.CreateModel(
            name='VoucherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherDetailNum', models.CharField(max_length=100, null=True, verbose_name='바우처그룹번호')),
                ('voucherPrice', models.IntegerField(verbose_name='제품가격')),
                ('discountRate', models.IntegerField(default=100, verbose_name='할인율')),
                ('wineQty', models.IntegerField(verbose_name='제품개수')),
                ('voucherSubTotal', models.IntegerField(verbose_name='총액')),
                ('vmVoucherUserLocation', models.CharField(max_length=100, null=True, verbose_name='사용처 저장')),
                ('isShipping', models.BooleanField(default=False, verbose_name='배송/픽업')),
                ('voucherExpDate', models.DateTimeField(null=True, verbose_name='만료일')),
                ('voucherQRImg', models.ImageField(null=True, upload_to='image/voucher_detail/%Y/%m/%d/', verbose_name='바우처QR이미지')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.item')),
                ('vm_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_mall.voucher')),
            ],
            options={
                'db_table': 'vm_voucher_detail',
            },
        ),
    ]
