# Generated by Django 3.2.13 on 2022-05-03 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionNumber', models.CharField(max_length=100, verbose_name='제품번호')),
                ('actionImage1', models.ImageField(null=True, upload_to='image/shop_master/auction/%Y/%m/%d/', verbose_name='와인이미지1')),
                ('actionImage2', models.ImageField(null=True, upload_to='image/shop_master/auction/%Y/%m/%d/', verbose_name='와인이미지2')),
                ('actionImage3', models.ImageField(null=True, upload_to='image/shop_master/auction/%Y/%m/%d/', verbose_name='와인이미지3')),
                ('auctionStartTime', models.DateTimeField(null=True, verbose_name='시작시간')),
                ('auctionEndTime', models.DateTimeField(null=True, verbose_name='종료시간')),
                ('auctionStartPrice', models.IntegerField(verbose_name='경매시작가격')),
                ('auctionBidPrice', models.IntegerField(verbose_name='제시금액단위')),
                ('auctionFinalPrice', models.IntegerField(verbose_name='낙찰가격')),
                ('auctionFinalUser', models.CharField(max_length=100, null=True, verbose_name='낙찰자')),
                ('auctionStatus', models.BooleanField(default=False, verbose_name='경매상황')),
                ('auctionDifferPrice', models.IntegerField(verbose_name='경매차액')),
                ('auctionBidderNum', models.IntegerField(verbose_name='경매참가자수')),
                ('auctionValuePrice', models.IntegerField(verbose_name='감정가')),
                ('auctionCurrentPrice', models.IntegerField(verbose_name='현재가')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'sm_auction',
            },
        ),
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardTypeName', models.CharField(max_length=100, verbose_name='유형이름')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'sm_board_type',
            },
        ),
        migrations.CreateModel(
            name='CategoryL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catLName', models.CharField(max_length=100, verbose_name='대분류이름')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'sm_cat_l',
            },
        ),
        migrations.CreateModel(
            name='CategoryS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catSName', models.CharField(max_length=100, verbose_name='소분류이름')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('cat_l', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.categoryl')),
            ],
            options={
                'db_table': 'sm_cat_s',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryNameEn', models.CharField(max_length=100, verbose_name='생산국가이름영문')),
                ('countryNameKr', models.CharField(max_length=100, verbose_name='생산국가이름한글')),
                ('countryImg', models.ImageField(null=True, upload_to='image/wine_master/country/', verbose_name='생산국가이미지')),
                ('countryDes', models.TextField(null=True, verbose_name='생산국가설명')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'wma_country',
            },
        ),
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grapeNameEn', models.CharField(max_length=100, verbose_name='포도이름영문')),
                ('grapeNameKr', models.CharField(max_length=100, verbose_name='포도이름한글')),
                ('grapeImg', models.ImageField(null=True, upload_to='image/wine_master/grape', verbose_name='포도이미지')),
                ('grapeDes', models.TextField(null=True, verbose_name='포도설명')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'wma_grape',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopItemNum', models.CharField(max_length=100, verbose_name='가맹점제품번호')),
                ('shopItemNameOne', models.CharField(max_length=100, null=True, verbose_name='가맹점제품명1')),
                ('shopItemNameTwo', models.CharField(max_length=100, null=True, verbose_name='가맹점제품명2')),
                ('shopItemImage', models.ImageField(null=True, upload_to='image/shop_master/item/', verbose_name='가맹점제품이미지')),
                ('shopItemVideo', models.FileField(null=True, upload_to='video/shop_master/item/%Y/%m/%d/', verbose_name='가맹점제품동영상')),
                ('shopItemDes', models.TextField(null=True, verbose_name='가맹점제품설명')),
                ('shopItemPrice', models.IntegerField(verbose_name='가맹정제품가격')),
                ('shopItemQty', models.IntegerField(verbose_name='가맹정제품재고수량')),
                ('isWine', models.BooleanField(default=True, verbose_name='가맹점제품구분자')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_cat_s', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.categorys')),
            ],
            options={
                'db_table': 'sm_item',
            },
        ),
        migrations.CreateModel(
            name='MonthPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=100, verbose_name='패키지이름')),
                ('startDate', models.DateTimeField(null=True, verbose_name='시작일')),
                ('endDate', models.DateTimeField(null=True, verbose_name='종료일')),
                ('packageImage', models.ImageField(null=True, upload_to='image/shop_master/package/', verbose_name='패키지이미지')),
                ('packageStatus', models.BooleanField(default=False, verbose_name='진행현황')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'sm_month_package',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionNameEn', models.CharField(max_length=100, verbose_name='지역이름영문')),
                ('regionNameKr', models.CharField(max_length=100, verbose_name='지역이름한글')),
                ('regionImg', models.ImageField(null=True, upload_to='image/wine_master/region/', verbose_name='지역이미지')),
                ('regionDes', models.TextField(null=True, verbose_name='지역설명')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'wma_region',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=100, verbose_name='가맹점이름')),
                ('shopPhone', models.CharField(max_length=20, null=True, verbose_name='가맹점연락처')),
                ('shopAddress', models.CharField(max_length=255, null=True, verbose_name='가맹점주소')),
                ('shopRegNum', models.CharField(max_length=20, null=True, verbose_name='가맹점사업자등록번호')),
                ('shopImage', models.ImageField(null=True, upload_to='image/shop_master/shop/', verbose_name='가맹점이미지')),
                ('shopPointRatio', models.IntegerField(verbose_name='기본적립금비율')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'sm_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeName', models.CharField(max_length=100, verbose_name='등급이름')),
                ('gradeLtdQty', models.IntegerField(verbose_name='상품등록개수')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'sma_shop_grade',
            },
        ),
        migrations.CreateModel(
            name='TodayReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayStartTime', models.DateTimeField(null=True, verbose_name='시작시간')),
                ('displayEndTime', models.DateTimeField(null=True, verbose_name='종료시간')),
                ('displayStatus', models.BooleanField(default=False, verbose_name='진행현황')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'sm_today_reg',
            },
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherTypeName', models.CharField(max_length=100, verbose_name='결제방식이름')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'vm_voucher_type',
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineryNameEn', models.CharField(max_length=100, verbose_name='와이너리이름영문')),
                ('wineryNameKr', models.CharField(max_length=100, verbose_name='와이너리이름한글')),
                ('wineryImg', models.ImageField(null=True, upload_to='image/wine_master/winery/', verbose_name='와이너리이미지')),
                ('wineryDes', models.TextField(null=True, verbose_name='외이너리설명')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'wma_winery',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineNum', models.CharField(max_length=100, verbose_name='와인제품번호')),
                ('wineNameEn', models.CharField(max_length=100, verbose_name='와인명영문')),
                ('wineNameKr', models.CharField(max_length=100, verbose_name='와인명영문')),
                ('wineImg', models.ImageField(null=True, upload_to='image/wine_master/wine/', verbose_name='와인이미지')),
                ('wineDes', models.TextField(null=True, verbose_name='와인설명')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('wma_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.country')),
                ('wma_grape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.grape')),
                ('wma_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.region')),
                ('wma_winery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.winery')),
            ],
            options={
                'db_table': 'wm_wine',
            },
        ),
        migrations.CreateModel(
            name='TodayWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineNum', models.CharField(max_length=100, verbose_name='제품번호')),
                ('todayWinePrice', models.IntegerField(verbose_name='제품가격')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='할인명')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_today_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='today_wine', to='system_manage.todayreg')),
                ('wm_wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.wine')),
            ],
            options={
                'db_table': 'sm_today_wine',
            },
        ),
        migrations.CreateModel(
            name='Summernote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sm_summernote',
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isStaff', models.BooleanField(default=False, verbose_name='관리자승급')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sm_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop')),
            ],
            options={
                'db_table': 'sm_shop_user',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='sma_shop_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop', to='system_manage.shopgrade'),
        ),
        migrations.CreateModel(
            name='MPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPPrice', models.IntegerField(verbose_name='차감포인트')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.item')),
            ],
            options={
                'db_table': 'wma_mp_item',
            },
        ),
        migrations.CreateModel(
            name='MonthWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineNum', models.CharField(max_length=100, verbose_name='제품번호')),
                ('monthWinePrice', models.IntegerField(verbose_name='제품가격')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('sm_month_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_wine', to='system_manage.monthpackage')),
                ('wn_wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.wine')),
            ],
            options={
                'db_table': 'sm_month_wine',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sm_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop'),
        ),
        migrations.AddField(
            model_name='item',
            name='wm_wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.wine'),
        ),
        migrations.CreateModel(
            name='AuctionBidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPirce', models.IntegerField(verbose_name='제시가')),
                ('isBestBidder', models.BooleanField(default=False, verbose_name='낙찰여부')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sm_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bidder', to='system_manage.auction')),
            ],
            options={
                'db_table': 'sm_auction_bidder',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='wm_wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction', to='system_manage.wine'),
        ),
    ]
