# Generated by Django 3.2.13 on 2022-04-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name_en', models.CharField(max_length=100, verbose_name='생산국가이름영문')),
                ('country_name_kr', models.CharField(max_length=100, verbose_name='생산국가이름한글')),
                ('country_img', models.CharField(max_length=255, null=True, verbose_name='생산국가이미지')),
                ('country_des', models.TextField(null=True, verbose_name='생산국가설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'wma_country',
            },
        ),
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grape_name_en', models.CharField(max_length=100, verbose_name='포도이름영문')),
                ('grape_name_kr', models.CharField(max_length=100, verbose_name='포도이름한글')),
                ('grape_img', models.CharField(max_length=255, null=True, verbose_name='포도이미지')),
                ('grape_des', models.TextField(null=True, verbose_name='포도설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'wma_grape',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name_en', models.CharField(max_length=100, verbose_name='지역이름영문')),
                ('region_name_kr', models.CharField(max_length=100, verbose_name='지역이름한글')),
                ('region_img', models.CharField(max_length=255, null=True, verbose_name='지역이미지')),
                ('region_des', models.TextField(null=True, verbose_name='지역설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'wma_region',
            },
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winery_name_en', models.CharField(max_length=100, verbose_name='와이너리이름영문')),
                ('winery_name_kr', models.CharField(max_length=100, verbose_name='와이너리이름한글')),
                ('winery_img', models.CharField(max_length=255, null=True, verbose_name='와이너리이미지')),
                ('winery_des', models.TextField(null=True, verbose_name='외이너리설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'wma_winery',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_num', models.CharField(max_length=100, verbose_name='와인제품번호')),
                ('wine_name_en', models.CharField(max_length=100, verbose_name='와인명영문')),
                ('wine_name_kr', models.CharField(max_length=100, verbose_name='와인명영문')),
                ('wine_img', models.CharField(max_length=255, null=True, verbose_name='와인이미지')),
                ('wine_des', models.TextField(null=True, verbose_name='와인설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='system_manage.country')),
                ('grape', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grape', to='system_manage.grape')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='region', to='system_manage.region')),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winery', to='system_manage.winery')),
            ],
            options={
                'db_table': 'wm_wine',
            },
        ),
    ]
