# Generated by Django 3.2.13 on 2022-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0003_auto_20220425_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='createdAt',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='updatedAt',
            new_name='updatedDate',
        ),
        migrations.RenameField(
            model_name='grape',
            old_name='createdAt',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='grape',
            old_name='updatedAt',
            new_name='updatedDate',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='createdAt',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='updatedAt',
            new_name='updatedDate',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='createdAt',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='winery',
            old_name='createdAt',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='winery',
            old_name='updatedAt',
            new_name='updatedDate',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='wine',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
    ]
