# Generated by Django 3.2.13 on 2022-04-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0004_auto_20220425_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=100, verbose_name='패키지이름')),
                ('startDate', models.DateField(null=True, verbose_name='시작일')),
                ('endDate', models.DateField(null=True, verbose_name='종료일')),
                ('packageImage', models.CharField(max_length=255, null=True, verbose_name='패키지이미지')),
                ('packageStatus', models.BooleanField(default=False, verbose_name='진행현황')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'sm_month_package',
            },
        ),
        migrations.CreateModel(
            name='MonthWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineNum', models.CharField(max_length=100, verbose_name='제품번호')),
                ('monthWinePrice', models.IntegerField(verbose_name='제품가격')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('month_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moth_package', to='system_manage.monthpackage')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_wine', to='system_manage.wine')),
            ],
            options={
                'db_table': 'sm_month_wine',
            },
        ),
    ]
