# Generated by Django 3.2.13 on 2022-04-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0005_monthpackage_monthwine'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayDate', models.DateField(null=True, verbose_name='게시일')),
                ('displayStartTime', models.DateTimeField(null=True, verbose_name='시작시간')),
                ('displayEndTime', models.DateTimeField(null=True, verbose_name='종료시간')),
                ('displayStatus', models.BooleanField(default=False, verbose_name='진행현황')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'sm_today_reg',
            },
        ),
        migrations.AlterField(
            model_name='monthwine',
            name='month_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_package', to='system_manage.monthpackage'),
        ),
        migrations.CreateModel(
            name='TodayWine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wineNum', models.CharField(max_length=100, verbose_name='제품번호')),
                ('monthWinePrice', models.IntegerField(verbose_name='제품가격')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('today_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='today_reg', to='system_manage.todayreg')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='today_wine', to='system_manage.wine')),
            ],
            options={
                'db_table': 'sm_today_wine',
            },
        ),
    ]
