# Generated by Django 3.2.13 on 2022-04-27 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_manage', '0006_auto_20220427_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionNumber', models.CharField(max_length=100, verbose_name='제품번호')),
                ('actionImage1', models.CharField(max_length=255, null=True, verbose_name='와인이미지1')),
                ('actionImage2', models.CharField(max_length=255, null=True, verbose_name='와인이미지2')),
                ('actionImage3', models.CharField(max_length=255, null=True, verbose_name='와인이미지3')),
                ('auctionStartTime', models.DateTimeField(null=True, verbose_name='시작시간')),
                ('auctionEndTime', models.DateTimeField(null=True, verbose_name='종료시간')),
                ('auctionStartPrice', models.IntegerField(verbose_name='경매시작가격')),
                ('auctionBidPrice', models.IntegerField(verbose_name='제시금액단위')),
                ('auctionFinalPrice', models.IntegerField(verbose_name='낙찰가격')),
                ('auctionFinalUser', models.CharField(max_length=100, verbose_name='낙찰자')),
                ('auctionStatus', models.BooleanField(default=False, verbose_name='경매상황')),
                ('auctionDifferPrice', models.IntegerField(verbose_name='경매차액')),
                ('auctionBidderNum', models.IntegerField(verbose_name='경매참가자수')),
                ('auctionValuePrice', models.IntegerField(verbose_name='감정가')),
                ('auctionCurrentPrice', models.IntegerField(verbose_name='현재가')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'sm_auction',
            },
        ),
        migrations.CreateModel(
            name='ShopGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeName', models.CharField(max_length=100, verbose_name='등급이름')),
                ('gradeLtdQty', models.IntegerField(verbose_name='상품등록개수')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'sma_shop_grade',
            },
        ),
        migrations.RenameField(
            model_name='todaywine',
            old_name='monthWinePrice',
            new_name='todayWinePrice',
        ),
        migrations.RemoveField(
            model_name='todayreg',
            name='displayDate',
        ),
        migrations.AddField(
            model_name='todaywine',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='할인명'),
        ),
        migrations.AlterField(
            model_name='monthpackage',
            name='endDate',
            field=models.DateTimeField(null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='monthpackage',
            name='startDate',
            field=models.DateTimeField(null=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='monthwine',
            name='month_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_wine', to='system_manage.monthpackage'),
        ),
        migrations.AlterField(
            model_name='monthwine',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.wine'),
        ),
        migrations.AlterField(
            model_name='todaywine',
            name='today_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='today_wine', to='system_manage.todayreg'),
        ),
        migrations.AlterField(
            model_name='todaywine',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.wine'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.country'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.grape'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.region'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.winery'),
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isStaff', models.BooleanField(default=False, verbose_name='관리자승급')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shopgrade')),
            ],
            options={
                'db_table': 'sm_shop_user',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=100, verbose_name='가맹점이름')),
                ('shopPhone', models.CharField(max_length=20, null=True, verbose_name='가맹점연락처')),
                ('shopAddress', models.CharField(max_length=255, null=True, verbose_name='가맹점주소')),
                ('shopRegNum', models.CharField(max_length=20, null=True, verbose_name='가맹점사업자등록번호')),
                ('shopImage', models.CharField(max_length=255, null=True, verbose_name='가맹점이미지')),
                ('shopPointRatio', models.IntegerField(verbose_name='기본적립금비율')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('shop_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop', to='system_manage.shopgrade')),
            ],
            options={
                'db_table': 'sm_shop',
            },
        ),
        migrations.CreateModel(
            name='AuctionBidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPirce', models.IntegerField(verbose_name='제시가')),
                ('isBestBidder', models.BooleanField(default=False, verbose_name='낙찰여부')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sm_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bidder', to='system_manage.auction')),
            ],
            options={
                'db_table': 'sm_auction_bidder',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction', to='system_manage.wine'),
        ),
    ]
