# Generated by Django 3.2.13 on 2022-04-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0007_auto_20220427_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catLName', models.CharField(max_length=100, verbose_name='대분류이름')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'db_table': 'sm_cat_l',
            },
        ),
        migrations.CreateModel(
            name='CategoryS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catSName', models.CharField(max_length=100, verbose_name='소분류이름')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('cat_l', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.categoryl')),
            ],
            options={
                'db_table': 'sm_cat_s',
            },
        ),
    ]
