# Generated by Django 3.2.13 on 2022-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0009_auto_20220427_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='regionImg',
            field=models.ImageField(blank=True, upload_to='image/wine_master/region', verbose_name='지역이미지'),
        ),
    ]
