# Generated by Django 3.2.13 on 2022-04-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0011_alter_region_regionimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='cat_l',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_manage.categoryl'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='sm_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_manage.shopgrade'),
        ),
    ]
