# Generated by Django 3.2.13 on 2022-04-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0012_auto_20220427_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryl',
            name='sm_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop'),
        ),
        migrations.AlterField(
            model_name='categorys',
            name='cat_l',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.categoryl'),
        ),
    ]
