# Generated by Django 3.2.13 on 2022-04-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0013_auto_20220427_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryl',
            name='sm_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='sm_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shopgrade'),
        ),
    ]
