# Generated by Django 3.2.13 on 2022-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0015_alter_shopuser_sm_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='actionImage1',
            field=models.ImageField(null=True, upload_to='image/shop_master/auction', verbose_name='와인이미지1'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='actionImage2',
            field=models.ImageField(null=True, upload_to='image/shop_master/auction', verbose_name='와인이미지2'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='actionImage3',
            field=models.ImageField(null=True, upload_to='image/shop_master/auction', verbose_name='와인이미지3'),
        ),
        migrations.AlterField(
            model_name='country',
            name='countryImg',
            field=models.ImageField(null=True, upload_to='image/wine_master/country', verbose_name='생산국가이미지'),
        ),
        migrations.AlterField(
            model_name='grape',
            name='grapeImg',
            field=models.ImageField(null=True, upload_to='image/wine_master/grape', verbose_name='포도이미지'),
        ),
        migrations.AlterField(
            model_name='monthpackage',
            name='packageImage',
            field=models.ImageField(null=True, upload_to='image/shop_master/package', verbose_name='패키지이미지'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopImage',
            field=models.ImageField(null=True, upload_to='image/shop_master/shop', verbose_name='가맹점이미지'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='wineImg',
            field=models.ImageField(null=True, upload_to='image/wine_master/wine', verbose_name='와인이미지'),
        ),
        migrations.AlterField(
            model_name='winery',
            name='wineryImg',
            field=models.ImageField(null=True, upload_to='image/wine_master/winery', verbose_name='와이너리이미지'),
        ),
    ]
