# Generated by Django 3.2.13 on 2022-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0016_auto_20220427_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shopItemImage',
            field=models.ImageField(null=True, upload_to='image/shop_master/item', verbose_name='가맹점제품이미지'),
        ),
        migrations.AlterField(
            model_name='region',
            name='regionImg',
            field=models.ImageField(null=True, upload_to='image/wine_master/region/%Y/%m/%d/', verbose_name='지역이미지'),
        ),
    ]
