# Generated by Django 3.2.13 on 2022-05-02 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_manage', '0021_remove_categoryl_sm_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Summernote',
        ),
        migrations.AlterModelTable(
            name='summernote',
            table='sm_summernote',
        ),
    ]
