# Generated by Django 3.2.13 on 2022-05-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0023_boardtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherTypeName', models.CharField(max_length=100, verbose_name='결제방식이름')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updatedDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'vm_voucher_type',
            },
        ),
        migrations.AlterField(
            model_name='auction',
            name='actionImage1',
            field=models.ImageField(null=True, upload_to='image/shop_master/auction/%Y/%m/%d/', verbose_name='와인이미지1'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='actionImage2',
            field=models.ImageField(null=True, upload_to='image/shop_master/auction/%Y/%m/%d/', verbose_name='와인이미지2'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='actionImage3',
            field=models.ImageField(null=True, upload_to='image/shop_master/auction/%Y/%m/%d/', verbose_name='와인이미지3'),
        ),
    ]
